### ISSUE TITLE
Replace call by value with call by references

### ISSUE THREAD

**Issue by rasitsimsek** [onfe/Completionist#1]
On several functions arguments are passed by value instead of by references. This causes a speed impact. 

Problematic way:
`pvc_t suggest (
  PhraseList pl,
  SegmentTree st,
  std::string prefix,
  uint32_t numResults = 16)`

Better way:
`pvc_t suggest (
  PhraseList& pl,
  SegmentTree& st,
  std::string& prefix,
  uint32_t numResults = 16`

In C++11 you can use emplace_back() instead of push_back(). It is more efficient.

For std::queue emplace can be used instead of push:
`queue.push(PhraseRange(first, last, best.first, best.second));`
vs.
`queue.emplace(first, last, best.first, best.second);`

Not good way:
`string complete(string inp)`

Better way_:
string complete(string& inp)

**Comment by onfe** [comment]
is `queue.emplace(first, last, best.first, best.second);` the same as `queue.push_back({first, last, best.first, best.second})` in terms of performance and result?

I think I'm still thinking of the less performant MS version of enqueue.
I'll take a look, thanks.

**Comment by rasitsimsek** [comment]
Yes it is similar, but with emplace the objects will be constructed at one place, the arguments are forwarded by the compiler and the object will be constructed on the right place.
